name: Auto Create Feature Branch

on:
  issues:
    types: [assigned]

permissions:
  contents: write

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all branches
        run: git fetch --all

      - name: Create branch
        run: |
          BASE_BRANCH="develop"
          BRANCH_NAME="features/${{ github.event.issue.title }}"
          
          # Vérifier si la branche de base existe, sinon utiliser main
          if ! git show-ref --verify --quiet refs/heads/$BASE_BRANCH; then
            BASE_BRANCH="main"
          fi

          git checkout $BASE_BRANCH
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
