name: Run Tests

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage > coverage_Node${{ matrix.node-version }}.txt

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage_Node${{ matrix.node-version }}
          path: coverage_Node${{ matrix.node-version }}.txt

